export const USER = {
  SIGNUP: 'SIGNUP',
  LOGIN: 'LOGIN',
  PROFILE: 'PROFILE',
  GET_USERS: 'GET_USERS',
  LOGOUT: 'LOGOUT'
}

export const CHAT = {
  GET_ALL_USERS_MESSAGES: 'GET_ALL_USERS_MESSAGES',
  LOGOUT: 'LOGOUT'
}
